module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert(
      'Products',
      [
        // Tapeos
        {
          name: 'Picada Barcelona',
          subcategoryId: 1,
          price: 400,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, 
        {
          name: 'Picada Veggie',
          subcategoryId: 1,
          price: 450,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, 
        {
          name: 'Picada Caliente',
          subcategoryId: 1,
          price: 680,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, 
        {
          name: 'Papas Fritas',
          subcategoryId: 1,
          price: 280,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, 
        {
          name: 'Papas con Cheddar',
          subcategoryId: 1,
          price: 400,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, 
        {
          name: 'Papas con Salsa Blanca',
          subcategoryId: 1,
          price: 380,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, 
        {
          name: 'Papas Bravas',
          subcategoryId: 1,
          price: 340,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, 
        {
          name: 'Papas Barcelona',
          subcategoryId: 1,
          price: 430,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, 
        {
          name: 'Papas Kids',
          subcategoryId: 1,
          price: 280,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, 
        {
          name: 'Muzzarelitas',
          subcategoryId: 1,
          price: 320,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, 
        {
          name: 'Aros de Cebolla',
          subcategoryId: 1,
          price: 300,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, 
        {
          name: 'Nachos',
          subcategoryId: 1,
          price: 200,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, 
        {
          name: 'Nuggets de Pollo',
          subcategoryId: 1,
          price: 300,
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        //Sandwiches 
        {
          name: 'Miga de Jamón Cocido',
          subcategoryId: 2,
          price: 400,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, 
        {
          name: 'Miga de Jamón Crudo',
          subcategoryId: 2,
          price: 500,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, 
        {
          name: 'Miga Primavera',
          subcategoryId: 2,
          price: 450,
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        // Pizzas
        {
          name: 'Soda Stereo',
          subcategoryId: 3,
          price: 480,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Patricio Rey',
          subcategoryId: 3,
          price: 500,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Las Pelotas',
          subcategoryId: 3,
          price: 500,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Los Piojos',
          subcategoryId: 3,
          price: 530,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Charly Garcia',
          subcategoryId: 3,
          price: 550,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Callejeros',
          subcategoryId: 3,
          price: 550,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Divididos',
          subcategoryId: 3,
          price: 600,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Kapanga',
          subcategoryId: 3,
          price: 650,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'La Beriso',
          subcategoryId: 3,
          price: 650,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Sumo',
          subcategoryId: 3,
          price: 650,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Bersuit Vergarabat',
          subcategoryId: 3,
          price: 650,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Fito Paez',
          subcategoryId: 3,
          price: 650,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Attaque 77',
          subcategoryId: 3,
          price: 650,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'La Renga',
          subcategoryId: 3,
          price: 650,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Spinetta',
          subcategoryId: 3,
          price: 650,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Viejas Locas',
          subcategoryId: 3,
          price: 650,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Barcelona',
          subcategoryId: 3,
          price: 700,
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        // Burgers
        {
          name: 'Rolling Stones',
          subcategoryId: 4,
          price: 350,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Queen',
          subcategoryId: 4,
          price: 400,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Barcelona',
          subcategoryId: 4,
          price: 450,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Pink Floyd',
          subcategoryId: 4,
          price: 370,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'The Beatles',
          subcategoryId: 4,
          price: 350,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Burger extra',
          subcategoryId: 4,
          price: 100,
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        // Postres
        {
          name: 'Almendrado',
          subcategoryId: 5,
          price: 170,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Bombón Escocés',
          subcategoryId: 5,
          price: 220,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Torta Chiara',
          subcategoryId: 5,
          price: 330,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Tiramisú casero',
          subcategoryId: 5,
          price: 280,
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        // Cervezas
        {
          name: 'Artesanal',
          subcategoryId: 6,
          price: 200,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Lata Schneider',
          subcategoryId: 6,
          price: 170,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Lata Heineken',
          subcategoryId: 6,
          price: 210,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Lata Patagonia',
          subcategoryId: 6,
          price: 270,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Lata Temple',
          subcategoryId: 6,
          price: 270,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Corona',
          subcategoryId: 6,
          price: 240,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Schneider x 1lt',
          subcategoryId: 6,
          price: 270,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Heineken/Stella Artois x 1lt',
          subcategoryId: 6,
          price: 380,
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        // Vinos
        {
          name: 'Chacabuco',
          subcategoryId: 7,
          price: 340,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Alma Mora (Chardonay)',
          subcategoryId: 7,
          price: 420,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Alma Mora (Malbec)',
          subcategoryId: 7,
          price: 440,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Santa Julia',
          subcategoryId: 7,
          price: 480,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Las Perdices',
          subcategoryId: 7,
          price: 600,
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        // Sin Alcohol
        {
          name: 'Agua / Agua con gas',
          subcategoryId: 8,
          price: 80,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, {
          name: 'Agua saborizada x 500ml',
          subcategoryId: 8,
          price: 140,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, {
          name: 'Gaseosa x 500ml',
          subcategoryId: 8,
          price: 140,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, {
          name: 'Speed',
          subcategoryId: 8,
          price: 150,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, {
          name: 'Exprimido de naranja',
          subcategoryId: 8,
          price: 270,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, {
          name: 'Limonada',
          subcategoryId: 8,
          price: 250,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, {
          name: 'Licuado',
          subcategoryId: 8,
          price: 200,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, {
          name: 'Café expresso',
          subcategoryId: 8,
          price: 110,
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        // Tragos
        {
          name: 'Fernet',
          subcategoryId: 9,
          price: 200,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, {
          name: 'Campari',
          subcategoryId: 9,
          price: 200,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, {
          name: 'Smirnoff',
          subcategoryId: 9,
          price: 250,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, {
          name: 'Dr. Lemon',
          subcategoryId: 9,
          price: 350,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, {
          name: 'Destornillador',
          subcategoryId: 9,
          price: 220,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, {
          name: 'Gancia',
          subcategoryId: 9,
          price: 200,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, {
          name: 'Gancia batido',
          subcategoryId: 9,
          price: 250,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, {
          name: 'Cuba libre',
          subcategoryId: 9,
          price: 280,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, {
          name: 'Whiscola',
          subcategoryId: 9,
          price: 250,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, {
          name: 'Daiquiri',
          subcategoryId: 9,
          price: 250,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, {
          name: 'Tequila Sunrise',
          subcategoryId: 9,
          price: 200,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, {
          name: 'Gin tonic',
          subcategoryId: 9,
          price: 380,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, {
          name: 'Absolut',
          subcategoryId: 9,
          price: 300,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, {
          name: 'Whisky con Speed',
          subcategoryId: 9,
          price: 300,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, {
          name: 'Caipiroska',
          subcategoryId: 9,
          price: 300,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, {
          name: 'Caipirinha',
          subcategoryId: 9,
          price: 300,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, {
          name: 'Negroni',
          subcategoryId: 9,
          price: 300,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, {
          name: 'Mojito',
          subcategoryId: 9,
          price: 320,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, {
          name: 'Margarita',
          subcategoryId: 9,
          price: 300,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, {
          name: 'Jagger',
          subcategoryId: 9,
          price: 380,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, {
          name: 'Malibu',
          subcategoryId: 9,
          price: 250,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, {
          name: 'White House',
          subcategoryId: 9,
          price: 250,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, {
          name: 'J y B',
          subcategoryId: 9,
          price: 350,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, {
          name: 'Johnnie Walker',
          subcategoryId: 9,
          price: 400,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, {
          name: 'Baileys',
          subcategoryId: 9,
          price: 350,
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        // Espumantes
        {
          name: 'Chandon + 1 speed',
          subcategoryId: 10,
          price: 900,
          createdAt: new Date(),
          updatedAt: new Date(),
        }
      ],
      {}
    );
  },
  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('Products', null, {});
  },
};
